### ISSUE TITLE
Trigger.ino will wear out the eeprom

### ISSUE THREAD

**Issue by sprouse** [adafruit/adafruit-io-basics#2]
The EPROMs in the ESP devices are rated at 100,000 program cycles. I think the trigger.ino program will hit this in under a week.

Instead of using the eeprom, one thing to try is to use a probabilistic approach. Initialize the random number generator by reading a floating analog input pin, then choose a random number In the range 0..N and update the battery if the RN is 0. 1/N is the average rate at which you want to update the battery status.

**Comment by toddtreece** [comment]
@sprouse nice catch! we'll look at taking a different approach

**Comment by brentru** [comment]
The EEPROM is reset with the new battery_count every time it cycles past BATTERY_INTERVAL https://github.com/brentru/Adafruit_Learning_System_Guides/blob/ccccf0fd8d822a46e5eb6341196cdbdcdcbefa48/IFTTT_Door_Detector/IFTTT_Door_Detector.ino#L61
