### ISSUE TITLE
problem to connect

### ISSUE THREAD

**Issue by ghost** [adafruit/adafruit-io-basics#5]
sir i try the gps example for adafruit fona 808 and i am getting this problem 
AT+CIPSTART="TCP","","1883" 
<--- +CME ERROR: operation not allowed 
Connection failed Retrying MQTT connection
 ---> AT+CIPSHUT
i am try all ways but i am always getting same problem please reply what should i do.

**Comment by brentru** [comment]
The Adafruit IO Arduino Library has an updated location example for the FONA, try using that one: https://github.com/adafruit/Adafruit_IO_Arduino/blob/master/examples/adafruitio_04_location/adafruitio_04_location.ino
